export default {
    UPDATE_TEMPERATURE: 'UPDATE_TEMPERATURE',
    ADD_PRODUCT_TO_FREEZER: 'ADD_PRODUCT_TO_FREEZER',
    PLACE_ORDER: 'PLACE_ORDER',
    FULLFILL_ORDER: 'FULLFILL_ORDER',
    PAY_FOR_ORDER: 'PAY_FOR_ORDER',
    CANCEL_ORDER: 'CANCEL_ORDER',
}